"""Schéma initial : utilisateurs, RBAC, magasins, stock par magasin, ventes, caisse, chat, audit.

Revision ID: 0a3a50d6f8d3
Revises: 
Create Date: 2026-10-02 15:15:04.004567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a3a50d6f8d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Compteur des numéros de vente (non détecté par l'autogénération, ajouté à la main).
    op.execute(sa.schema.CreateSequence(sa.Sequence("sale_number_seq")))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('name', name=op.f('uq_stores_name'))
    )
    op.create_index('uq_stores_single_default', 'stores', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('purchase_price >= 0', name=op.f('ck_products_purchase_price_not_negative')),
    sa.CheckConstraint('selling_price >= 0', name=op.f('ck_products_selling_price_not_negative')),
    sa.CheckConstraint('stock >= 0', name=op.f('ck_products_stock_not_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('reference', name=op.f('uq_products_reference'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_users_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_store_id'), 'users', ['store_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cashregisterstatus', native_enum=False, length=30), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('opening_amount >= 0', name=op.f('ck_cash_registers_opening_amount_not_negative')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_cash_registers_closed_by_users')),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], name=op.f('fk_cash_registers_opened_by_users')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_cash_registers_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_registers'))
    )
    op.create_index(op.f('ix_cash_registers_status'), 'cash_registers', ['status'], unique=False)
    op.create_index(op.f('ix_cash_registers_store_id'), 'cash_registers', ['store_id'], unique=False)
    op.create_index('uq_cash_registers_one_open_per_store', 'cash_registers', ['store_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', name='conversationtype', native_enum=False, length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversations_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_number', sa.String(length=30), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_type', sa.Enum('NONE', 'PERCENTAGE', 'FIXED', name='discounttype', native_enum=False, length=30), server_default='NONE', nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELLED', name='salestatus', native_enum=False, length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0 AND discount_amount <= subtotal', name=op.f('ck_sales_discount_amount_valid')),
    sa.CheckConstraint('discount_value >= 0', name=op.f('ck_sales_discount_value_not_negative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_sales_subtotal_not_negative')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_sales_total_not_negative')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sales_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sales_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales')),
    sa.UniqueConstraint('sale_number', name=op.f('uq_sales_sale_number'))
    )
    op.create_index('ix_sales_created_at', 'sales', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_index(op.f('ix_sales_store_id'), 'sales', ['store_id'], unique=False)
    op.create_index(op.f('ix_sales_user_id'), 'sales', ['user_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ENTRY', 'EXIT', 'SALE', 'RETURN', 'ADJUSTMENT', 'LOSS', 'TRANSFER_OUT', 'TRANSFER_IN', name='stockmovementtype', native_enum=False, length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity <> 0', name=op.f('ck_stock_movements_quantity_not_zero')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_stock_movements_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_movements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index('ix_stock_movements_created_at', 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference'), 'stock_movements', ['reference'], unique=False)
    op.create_index(op.f('ix_stock_movements_store_id'), 'stock_movements', ['store_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_user_id'), 'stock_movements', ['user_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_store_id', sa.Integer(), nullable=False),
    sa.Column('destination_store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_transfers_quantity_positive')),
    sa.CheckConstraint('source_store_id <> destination_store_id', name=op.f('ck_stock_transfers_different_stores')),
    sa.ForeignKeyConstraint(['destination_store_id'], ['stores.id'], name=op.f('fk_stock_transfers_destination_store_id_stores')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_transfers_product_id_products')),
    sa.ForeignKeyConstraint(['source_store_id'], ['stores.id'], name=op.f('fk_stock_transfers_source_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_transfers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfers'))
    )
    op.create_index('ix_stock_transfers_created_at', 'stock_transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_transfers_destination_store_id'), 'stock_transfers', ['destination_store_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_product_id'), 'stock_transfers', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_source_store_id'), 'stock_transfers', ['source_store_id'], unique=False)
    op.create_table('store_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_store_stocks_quantity_not_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_store_stocks_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_stocks_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_stocks')),
    sa.UniqueConstraint('store_id', 'product_id', name=op.f('uq_store_stocks_store_id_product_id'))
    )
    op.create_index(op.f('ix_store_stocks_product_id'), 'store_stocks', ['product_id'], unique=False)
    op.create_index(op.f('ix_store_stocks_store_id'), 'store_stocks', ['store_id'], unique=False)
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'EXPENSE', 'WITHDRAWAL', 'DEPOSIT', 'REFUND', 'ADJUSTMENT', name='cashtransactiontype', native_enum=False, length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_cash_transactions_amount_not_zero')),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], name=op.f('fk_cash_transactions_cash_register_id_cash_registers')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cash_transactions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_transactions'))
    )
    op.create_index(op.f('ix_cash_transactions_cash_register_id'), 'cash_transactions', ['cash_register_id'], unique=False)
    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_members_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id', name=op.f('pk_conversation_members'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'MOBILE_MONEY', 'CARD', 'BANK_TRANSFER', 'CREDIT', name='paymentmethod', native_enum=False, length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_not_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payments_created_by_users')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_payments_sale_id_sales')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_sale_id'), 'payments', ['sale_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_reference', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sale_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sale_items_unit_price_not_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sale_items_product_id_products')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_sale_items_sale_id_sales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_items'))
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_payments_sale_id'), table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversation_members')
    op.drop_index(op.f('ix_cash_transactions_cash_register_id'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_index(op.f('ix_store_stocks_store_id'), table_name='store_stocks')
    op.drop_index(op.f('ix_store_stocks_product_id'), table_name='store_stocks')
    op.drop_table('store_stocks')
    op.drop_index(op.f('ix_stock_transfers_source_store_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_product_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_destination_store_id'), table_name='stock_transfers')
    op.drop_index('ix_stock_transfers_created_at', table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_movements_user_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_store_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_created_at', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_sales_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_store_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index('ix_sales_created_at', table_name='sales')
    op.drop_table('sales')
    op.drop_table('conversations')
    op.drop_index('uq_cash_registers_one_open_per_store', table_name='cash_registers', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_cash_registers_store_id'), table_name='cash_registers')
    op.drop_index(op.f('ix_cash_registers_status'), table_name='cash_registers')
    op.drop_table('cash_registers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_store_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('uq_stores_single_default', table_name='stores', postgresql_where=sa.text('is_default'))
    op.drop_table('stores')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('categories')
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("sale_number_seq")))
