"""Société, copie société/magasin sur chaque facture, prix de stock figé sur les lignes de vente,
règle prix de vente >= prix de stock, révocation des jetons (token_version).

Revision ID: 8732f6c28354
Revises: adb874fd17fe
Create Date: 2026-10-02 16:34:44.706745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8732f6c28354'
down_revision: Union[str, Sequence[str], None] = 'adb874fd17fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_company_information_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_information'))
    )
    op.create_table('invoice_company_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('store_address', sa.String(length=255), nullable=True),
    sa.Column('store_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_invoice_company_snapshots_sale_id_sales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_company_snapshots')),
    sa.UniqueConstraint('sale_id', name=op.f('uq_invoice_company_snapshots_sale_id'))
    )
    # Lignes de vente existantes : prix de stock actuel du produit (meilleure valeur connue).
    op.add_column('sale_items', sa.Column('unit_purchase_price', sa.Numeric(precision=14, scale=2), nullable=True))
    op.execute(
        "UPDATE sale_items SET unit_purchase_price = products.purchase_price "
        "FROM products WHERE products.id = sale_items.product_id"
    )
    op.alter_column('sale_items', 'unit_purchase_price', nullable=False)
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # Règle métier (non détectée par l'autogénération) : prix de vente >= prix de stock.
    # Si des produits existants violent la règle, PostgreSQL refuse la migration : corrigez-les d'abord.
    op.create_check_constraint(
        op.f("ck_products_selling_price_not_below_purchase_price"), "products", "selling_price >= purchase_price"
    )
    # Ventes antérieures : la société n'était pas encore enregistrée, leur facture reçoit un en-tête
    # générique (jamais les informations actuelles) et le magasin tel qu'il est aujourd'hui.
    op.execute(
        "INSERT INTO invoice_company_snapshots "
        "(sale_id, company_name, store_name, store_address, store_phone, created_at) "
        "SELECT sales.id, 'SOCIÉTÉ', stores.name, stores.address, stores.phone, sales.created_at "
        "FROM sales JOIN stores ON stores.id = sales.store_id"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_products_selling_price_not_below_purchase_price"), "products", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_column('sale_items', 'unit_purchase_price')
    op.drop_table('invoice_company_snapshots')
    op.drop_table('company_information')
    # ### end Alembic commands ###
